# Enable JetStream
jetstream {
    store_dir: "/data"
    max_mem_store: 1G
    max_file_store: 100G
}


http_port: 8222

accounts {
    SYS {
        users = [
            { user: $NATS_SYS_USER, password: $NATS_SYS_PASSWORD }
        ]
    }

    APP {
        users = [
            { user: $NATS_APP_USER, password: $NATS_APP_PASSWORD }
        ]
    }
}

# Designate SYS as the system account
system_account: SYS