serve:
  proxy:
    port: 4455
  api:
    port: 4456

log:
  level: debug
  format: text
  leak_sensitive_values: true
  
access_rules:
  repositories:
    - file:///etc/config/oathkeeper/rules/access-rules.yml

authenticators:
  noop:
    enabled: true
    
  bearer_token:
    enabled: true
    config:
      check_session_url: http://taksa-kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      token_from:
        header: Authorization  

  cookie_session:
    enabled: true
    config:
      check_session_url: http://taksa-kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      only:
        - ory_kratos_session

authorizers:
  allow:
    enabled: true

mutators:
  noop:
    enabled: true

  id_token:
    enabled: true
    config:
      jwks_url: file:///etc/config/oathkeeper/id_token.jwks.json
      ttl: 1h
      claims: |
        {
          "sub": "{{ .Subject }}",
          "email": "{{ .Extra.identity.traits.email }}",
          "role": "{{ .Extra.identity.traits.role }}",
          "organization_name": "{{ .Extra.identity.traits.organization_name }}"
        }

