serve:
  proxy:
    port: 4455
  api:
    port: 4456

log:
  level: debug
  format: text

access_rules:
  repositories:
    - file:///etc/config/oathkeeper/rules/access-rules.yml

authenticators:
  bearer_token:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      token_from:
        header: Authorization

  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      only:
        - ory_kratos_session

authorizers:
  allow:
    enabled: true

mutators:
  id_token:
    enabled: true
    config:
      # issuer_url: http://172.25.60.23:4455
      jwks_url: file:///etc/config/oathkeeper/id_token.jwks.json
      ttl: 1h
      claims: '{"sub": "{{ .Subject }}", "email": "{{ .Extra.identity.traits.email }}"}'