apiVersion: 1

datasources:

  - name: Taksa-TSDB
    type: postgres
    access: proxy
    orgId: 1
    url: taksa-tsdb:5432
    user: ${TSDB_PG_USER}
    isDefault: true
    editable: true
    secureJsonData:
      password: ${TSDB_PG_PASSWORD}
    jsonData:
      database: ${TSDB_PG_DB}
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true