services:
  taksa-ory-db:
    image: postgres:18
    container_name: taksa-ory-db
    ports:
      - "${KRATOS_PG_PORT}:5432"
    environment:
      - POSTGRES_USER=${KRATOS_PG_USER}
      - POSTGRES_PASSWORD=${KRATOS_PG_PASSWORD}
      - POSTGRES_DB=${KRATOS_PG_DB}
    volumes:
      - taksa-ory-data:/var/lib/postgresql
    networks:
      - taksa-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  kratos-migrate:
    image: oryd/kratos:v1.2.0
    environment:
      - DSN=${KRATOS_DSN}
      #- DSN=postgres://kratos:secret@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ../config/ory-stack/kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    networks:
      - taksa-network
    depends_on:
      taksa-ory-db:
        condition: service_healthy

  taksa-kratos:
    image: oryd/kratos:v1.2.0
    container_name: taksa-kratos
    ports:
      - "${KRATOS_PUBLIC_PORT}:4433"
      - "${KRATOS_ADMIN_PORT}:4434"
    environment:
      - DSN=${KRATOS_DSN}
      #- DSN=postgres://kratos:secret@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=debug
      # all these urls below were set in the config file but now as we are using emv vard we initialize them here rather then im the config file 
      - SERVE_PUBLIC_BASE_URL=http://${TAKSA_HOST_IP}:${KRATOS_PUBLIC_PORT}/
      - SERVE_ADMIN_BASE_URL=http://${TAKSA_HOST_IP}:${KRATOS_ADMIN_PORT}/
      - SESSION_COOKIE_DOMAIN=${TAKSA_HOST_IP}
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=http://${TAKSA_HOST_IP}:${KRATOS_PUBLIC_PORT},http://${TAKSA_HOST_IP}:${KRATOS_ADMIN_PORT},http://${TAKSA_HOST_IP}:${OATHKEEPER_PROXY_PORT},http://localhost:3000
      - SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=http://${TAKSA_HOST_IP}:${KRATOS_PUBLIC_PORT}/
      - SELFSERVICE_ALLOWED_RETURN_URLS=http://${TAKSA_HOST_IP}:${KRATOS_PUBLIC_PORT},http://${TAKSA_HOST_IP}:${KRATOS_ADMIN_PORT},http://localhost:3000
      - SELFSERVICE_FLOWS_ERROR_UI_URL=http://${TAKSA_HOST_IP}:${KRATOS_PUBLIC_PORT}/error
      - SELFSERVICE_FLOWS_SETTINGS_UI_URL=http://${TAKSA_HOST_IP}:${KRATOS_PUBLIC_PORT}/settings
      - SELFSERVICE_FLOWS_RECOVERY_UI_URL=http://${TAKSA_HOST_IP}:${KRATOS_PUBLIC_PORT}/recovery
      - SELFSERVICE_FLOWS_LOGIN_UI_URL=http://${TAKSA_HOST_IP}:${KRATOS_PUBLIC_PORT}/login
      - SELFSERVICE_FLOWS_REGISTRATION_UI_URL=http://${TAKSA_HOST_IP}:${KRATOS_PUBLIC_PORT}/registration
    
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - ../config/ory-stack/kratos:/etc/config/kratos
    networks:
      - taksa-network
    restart: unless-stopped
    depends_on:
      - kratos-migrate

  taksa-oathkeeper:
    image: oryd/oathkeeper:v0.40
    container_name: taksa-oathkeeper
    ports:
      - "${OATHKEEPER_PROXY_PORT}:4455"
      - "${OATHKEEPER_API_PORT}:4456"
    environment:
      - AUTHENTICATORS_BEARER_TOKEN_CONFIG_CHECK_SESSION_URL=http://taksa-kratos:4433/sessions/whoami
      - AUTHENTICATORS_COOKIE_SESSION_CONFIG_CHECK_SESSION_URL=http://taksa-kratos:4433/sessions/whoami
      - MUTATORS_ID_TOKEN_CONFIG_ISSUER_URL=http://${TAKSA_HOST_IP}:${OATHKEEPER_PROXY_PORT}
    
    command: serve -c /etc/config/oathkeeper/oathkeeper.yml
    volumes:
      - ../config/ory-stack/oathkeeper:/etc/config/oathkeeper
    networks:
      - taksa-network
    restart: unless-stopped
    depends_on:
      - taksa-kratos

  taksa-mailslurper:
    image: oryd/mailslurper:latest-smtps
    container_name: taksa-mailslurper
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - taksa-network

  taksa-tsdb:
    image: timescale/timescaledb:latest-pg18
    container_name: taksa-tsdb
    ports:
      - "${TSDB_PG_PORT}:5432"
    environment:
      - POSTGRES_USER=${TSDB_PG_USER}
      - POSTGRES_PASSWORD=${TSDB_PG_PASSWORD}
      - POSTGRES_DB=${TSDB_PG_DB}
    volumes:
      - taksa-ts-data:/var/lib/postgresql
      - ../config/database/schemas:/docker-entrypoint-initdb.d:ro
    networks:
      - taksa-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  taksa-nats:
    image: nats:latest
    container_name: taksa-nats
    command: ["-c", "/config/nats-server.conf"]
    ports:
      - "${TAKSA_NATS_SERVER_PORT}:4222" # Client port
      - "${TAKSA_NATS_MONITOR_PORT}:8222" # HTTP Monitoring port
    environment:
      - NATS_SYS_USER=${TAKSA_NATS_SYS_USER}
      - NATS_SYS_PASSWORD=${TAKSA_NATS_SYS_PASSWORD}
    volumes:
      - ../config/nats/nats-server.conf:/config/nats-server.conf:ro
      - taksa-nats-data:/data

  taksa-apigateway:
    #image: haproxy:3.2-alpine
    image: haproxy:3.2
    container_name: taksa-apigateway
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"
    volumes:
      - ../config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      #- ../config/haproxy/entrypoint.sh:/entrypoint.sh
      - ../config/haproxy/errors:/usr/local/etc/haproxy/errors:ro
      - ../config/certs:/usr/local/etc/haproxy/certs:ro
    environment:
      - OATHKEEPER_HOST=taksa-oathkeeper
      - OATHKEEPER_PORT=4455
      - BACKEND_HOST=taksa-ui
      - BACKEND_PORT=8080
    networks:
      - taksa-network
    depends_on:
      - taksa-oathkeeper
    restart: unless-stopped
    #entrypoint: ["/bin/sh", "/entrypoint.sh"]

  taksa-ui:
    image: nginx:alpine
    container_name: taksa-ui
    volumes:
      - ../tests/test-ui/index.html:/usr/share/nginx/html/index.html:ro
      - ../tests/test-ui/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - taksa-network
    restart: unless-stopped

volumes:
  taksa-ory-data:
   driver_opts:
     type: 'none'
     o: 'bind'
     device: '${TAKSA_DATADIR}/taksa/data/ory-db'
  taksa-ts-data:
   driver_opts:
     type: 'none'
     o: 'bind'
     device: '${TAKSA_DATADIR}/taksa/data/timescale-db'
  taksa-nats-data:
   driver_opts:
     type: 'none'
     o: 'bind'
     device: '${TAKSA_DATADIR}/taksa/data/nats-data'

networks:
  taksa-network:
    driver: bridge
